# Config file for automatic testing at travis-ci.org
# Inspired by https://github.com/soft-matter/trackpy/blob/master/.travis.yml

language: python
# installing requirements.txt takes 5 minutes, mostly due to matplotlib
cache: pip

python:
  - "2.7"

before_install:
  # install conda to help with numpy/scipy system dependencies
  - wget https://repo.continuum.io/miniconda/Miniconda2-4.0.5-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - export CONDA_PREFIX=/home/travis/mc
  - ./miniconda.sh -b -p "$CONDA_PREFIX"
  - export PATH="$CONDA_PREFIX/bin":$PATH

  # install matplotlib system dependencies
  - sudo apt-get -qq update
  - sudo apt-get install -y libx11-dev 
  
  # install msgsteiner dependencies
  - sudo apt-get install -y libboost-dev libboost-program-options-dev

  # install msgsteiner
  - wget http://areeweb.polito.it/ricerca/cmp/sites/default/files/msgsteiner-1.1.tgz
  - tar xzf msgsteiner-1.1.tgz
  - cd msgsteiner-1.1
  - patch Makefile ../patches/Makefile.linux.patch
  - make
  - [ -e "msgsteiner" ] && export MSGSTEINER_PATH="$(pwd -P)/msgsteiner"
  - cd ..

install: 
  # setup python environment
  - conda create -n testenv -y pip setuptools python=$TRAVIS_PYTHON_VERSION
  - source activate testenv

  # debug
  - echo $PATH
  - echo $MSGSTEINER_PATH
  - echo $CONDA_PREFIX

  # install python dependencies
  - pip install -r requirements.txt

  # also install test dependencies
  - pip install pytest>=2.9.2

  # install our package
  - python setup.py install

script: python setup.py test -a "--msgpath=$MSGSTEINER_PATH"
